print("Hej på dig lill grabben!")
print("Vad heter du?")
namn = input ()
print("Hej", namn, "kul att du är här")
print("Hur gammal är du?")
ålder = input ()
print("wow!", namn, "du är", ålder, "är gammal helvete!")
print("Hur mår du då?")
svar = input ()
print("Varför mår du", svar, "?")
